Reenable code quality and code coverage

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,5 +1,5 @@
 variables:
-  BASE_IMAGE_NAME: registry.gitlab.com/squey/container-images/squey_build:9df6a34a
+  BASE_IMAGE_NAME: registry.gitlab.com/squey/container-images/squey_build:166ed698
   GIT_SUBMODULE_STRATEGY: recursive
   CACHE_COMPRESSION_LEVEL: "fastest"
   CODE_COVERAGE:
@@ -27,14 +27,18 @@ cancel_scheduled_pipeline_if_already_ran_for_this_commit:
   stage: check
   script:
     - |
-      existing_pipeline=$(curl --silent --header "PRIVATE-TOKEN: $CI_JOB_TOKEN" \
-        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines?sha=$CI_COMMIT_SHA" | jq '.[] | select(.id != '$CI_PIPELINE_ID')')
+      # Only look at scheduled pipelines, otherwise the merge request pipeline which
+      # already ran on this commit would be enough to cancel this one
+      existing_pipeline=$(curl --silent --get \
+        --data-urlencode "sha=$CI_COMMIT_SHA" \
+        --data-urlencode "source=schedule" \
+        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines" | jq ".[] | select(.id != $CI_PIPELINE_ID)")
       if [ -n "$existing_pipeline" ]; then
         echo "Already built, skipping pipeline."
-        curl --request POST --form token="$CI_JOB_TOKEN" \
-          --form ref="$CI_COMMIT_REF_NAME" \
-          "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipeline/cancel"
-        exit 0
+        if ! curl --silent --fail --request POST --header "PRIVATE-TOKEN: $GITLAB_API_TOKEN" \
+             "$CI_API_V4_URL/projects/$CI_PROJECT_ID/pipelines/$CI_PIPELINE_ID/cancel" > /dev/null; then
+          echo "Could not cancel the pipeline, check that GITLAB_API_TOKEN is set with the 'api' scope"
+        fi
       fi
   rules:
     - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
@@ -125,7 +129,7 @@ build testsuite windows:
       --export=true
       --export-dir="$CI_PROJECT_DIR/export"
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CODE_COVERAGE != "true"'
       when: always
     - if: "$CI_MERGE_REQUEST_LABELS =~ /(^|,)export_windows_package(,|$)/"
       when: always
@@ -152,7 +156,7 @@ build testsuite macos:
       --export=true
       --export-dir="$CI_PROJECT_DIR/export"
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CODE_COVERAGE != "true"'
       when: always
     - if: "$CI_MERGE_REQUEST_LABELS =~ /(^|,)export_macos_package(,|$)/"
       when: always
@@ -181,7 +185,7 @@ build release macos:
       --export=true
       --export-dir="$CI_PROJECT_DIR/export"
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CODE_COVERAGE != "true"'
       when: always
     - if: '$CI_COMMIT_TAG =~ /^release-\d+\.\d+\.\d+$/'
       when: always
@@ -226,7 +230,7 @@ run testsuite windows:
   script:
     - !reference [.run testsuite windows]
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CODE_COVERAGE != "true"'
       when: always
     - if: "$CI_MERGE_REQUEST_LABELS =~ /(^|,)export_windows_package(,|$)/"
       when: always
@@ -243,7 +247,7 @@ run testsuite macos:
   script:
     - !reference [.run testsuite macos]
   rules:
-    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
+    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CODE_COVERAGE != "true"'
       when: always
     - if: "$CI_MERGE_REQUEST_LABELS =~ /(^|,)export_macos_package(,|$)/"
       when: always
@@ -312,7 +316,7 @@ pages:
   tags:
     - privileged-docker
   before_script:
-    - mkdir -p $CI_PROJECT_DIR/public/code_quality_report
+    - mkdir -p $CI_PROJECT_DIR/public
   script:
     - |
       VERSION=$(cat $CI_PROJECT_DIR/VERSION.txt | tr -d '\n')
@@ -320,8 +324,9 @@ pages:
       JOB_ID=`curl -s -X GET ${CI_API_V4_URL}/projects/squey%2Fsquey/pipelines/${PIPELINE_ID}/jobs | jq -r '.[] | select(.stage=="pages") | .id'`
       if [ "$CODE_COVERAGE" = "true" ]; then
         curl -XGET -L ${CI_PROJECT_URL}/-/jobs/${JOB_ID}/artifacts/download | bsdtar -xvf- || true
-        rm -rf $CI_PROJECT_DIR/public/code_coverage_report
+        rm -rf $CI_PROJECT_DIR/public/code_coverage_report $CI_PROJECT_DIR/public/code_quality_report
         mv code_coverage_report $CI_PROJECT_DIR/public
+        mv code_quality_report $CI_PROJECT_DIR/public || true # the code quality job is allowed to fail
         exit 0
       fi
       ostree checkout -U --repo="$CI_PROJECT_DIR/public/flatpak" app/org.squey.Squey/x86_64/release-$VERSION public/flatpak_app && cd public/flatpak_app && XZ_OPT=-9T0 tar Jcvf "$CI_PROJECT_DIR/public/squey_flatpak_$VERSION.tar.xz" . && cd - && rm -rf "$CI_PROJECT_DIR/public/flatpak_app"
@@ -338,13 +343,24 @@ pages:
     expire_in: 1 day
   rules:
     - if: '$CI_COMMIT_TAG =~ /^release-\d+\.\d+\.\d+$/ || $CODE_COVERAGE == "true"'
+  # Release and code coverage pipelines do not run the same set of jobs, so every
+  # dependency has to be optional for the pipeline to be created in both cases
   needs:
+    - job: build and run testsuite linux
+      artifacts: true
+      optional: true
+    - job: code_quality
+      artifacts: true
+      optional: true
     - job: build release linux
       artifacts: true
+      optional: true
     - job: build testsuite windows
       artifacts: true
+      optional: true
     - job: macos_publish
       artifacts: true
+      optional: true
   interruptible: true
 
 flathub:
@@ -379,6 +395,37 @@ flathub:
   rules:
     - if: $CI_COMMIT_TAG =~ /^release-\d+\.\d+\.\d+$/
 
+code_quality:
+  stage: static_analysis
+  image:
+    name: "$BASE_IMAGE_NAME"
+    pull_policy: [if-not-present]
+  tags:
+    - privileged-docker
+  needs: []
+  variables:
+    # Only fetch the submodules holding source code we analyze, the test suite
+    # one is too big to be worth cloning here
+    GIT_SUBMODULE_STRATEGY: normal
+    GIT_SUBMODULE_PATHS: src/furl src/squey-utils src/libpvcop
+    GIT_SUBMODULE_DEPTH: 1
+  script:
+    - .gitlab-ci/code_quality.sh
+  artifacts:
+    when: always
+    reports:
+      codequality: gl-code-quality-report.json
+    paths:
+      - gl-code-quality-report.json
+      - code_quality_report
+    expire_in: 1 week
+  rules:
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
+    - if: '$CI_PIPELINE_SOURCE == "schedule"'
+    - if: '$CODE_COVERAGE == "true"'
+  interruptible: true
+  allow_failure: true
+
 sast:
   variables:
     SAST_EXCLUDED_PATHS: external, tests, doc
@@ -390,22 +437,20 @@ sast:
     - privileged-docker
 include:
   - template: Security/SAST.gitlab-ci.yml
-  #- template: Code-Quality.gitlab-ci.yml
   #- template: Jobs/Secret-Detection.latest.gitlab-ci.yml
   - template: Jobs/Container-Scanning.gitlab-ci.yml
 
 semgrep-sast:
+  variables:
+    # Submodules hold code which is analyzed by their own project pipeline
+    GIT_SUBMODULE_STRATEGY: none
   rules:
+    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
     - if: '$CI_PIPELINE_SOURCE == "schedule"'
+  interruptible: true
+
 #secret_detection:
 #  rules:
 #    - if: '$CI_PIPELINE_SOURCE == "push"'
 #    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
 #  interruptible: true
-
-#code_quality_html:
-#  extends: code_quality
-#  variables:
-#    REPORT_FORMAT: html
-#  artifacts:
-#    paths: [gl-code-quality-report.html]
